addons:
  postgresql: '9.4'
language: ruby
cache: bundler
notifications:
  slack: excella-4th:D0zR7CRDJdhg07kKkO2Axq9Y
rvm:
- 2.2.2
branches:
  only:
  - master
before_script:
- rake db:create db:migrate
- rake db:create db:migrate RAILS_ENV=travis
script:
- bundle exec brakeman
- bundle exec rubocop -Dc .rubocop.yml
- RAILS_ENV=travis bundle exec rspec
- bundle exec rake teaspoon
- rake cucumber:non_exterior RAILS_ENV=travis secret_key_base=$SECRET_KEY_BASE
- rake cucumber:exterior_integration RAILS_ENV=travis secret_key_base=$SECRET_KEY_BASE
deploy:
  provider: heroku
  run:
  - rake db:migrate
  - restart
  app:
    master: open-cabinet
  api_key:
    secure: svGpW+jZ2cAbPXMHpS8eFuxDSC3Z4VEgZ+7o14vfWPYOojn1AGjs3j9z9Ft4AVgLS6WmtWSGsxEmcFISYB3ujJQE/oscFVdR2DYntLdl0FEJ0KHEM6jVdhClGQmVqjRLIOLfl1mOpUTWTIMRD+egsTTIkQq6LGqUpFOla4i3WiI6d0G7CgLf+IRLS4VwzPLjGlvRFCngPBqBi+HnEovVk8VJm03azpVSO1+cS7QHvlYTwY3GYpNWIxhHwSVpbNHB96ZPbYnYxXuyVq+t8wW4T/IGO+4UQzraLx5Fv++Ip+xcTd7MUWnFOC6meG32s+Y4c1pOVOEn/93IC5CQeFySDTSy7uDqLjT7y2JoV7zVij40x9KfOcB+87/qYUoNAjxkHpG/S1peinIYGTHdscckFfv+vjW1zh/fUU6bS++Mcv9WHhZuWAbFOwOoM0ZJuKaDioAkzqGW98WOBM5JoX+yr29XdJdle3IwvQXzDF3fGvXCqu3qTbUCIFi7j1Lo/E+sF5pu+c2hi7utG0CzXV+3lkKzsXn/vCtYnCcy20N+tqiBEhf7H+kyc1JT5ULelNcIqQv3Gki8tSXN6P2tAOL7YxWPmPbD3gCH/Kd6NAfjo2LsAUPUiTskJfWcNS9IU9oJOF+1ju161PFxGnK/JwA5Thq1Q2yFo43yV012I9vQX+o=
